let stockProductos = [
  {
    // zapatillas
    id: 1,
    nombre: "jordan 23",
    tipo: "zapatilla",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "67200",
    talle: "39",
    img: `./img/jordan/hunter-johnson-0UCGfN2qtrs-unsplash.jpg`,
  },
  {
    id: 2,
    nombre: "jordan 1",
    tipo: "zapatilla",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "67200",
    talle: "38",
    img: `./img/jordan/paul-volkmer-crRwoRukgkA-unsplash.jpg`,
  },
  {
    id: 3,
    nombre: "jordan 4 retro",
    tipo: "zapatilla",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "67200",
    talle: "40",
    img: `./img/jordan/lewis-pugsley-KeAJ36SRgdw-unsplash.jpg`,
  },
  {
    id: 4,
    nombre: "jordan 11",
    tipo: "zapatilla",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "67200",
    talle: "38",
    img: `./img/jordan/taylor-smith-Crs7t2Iv6Z4-unsplash.jpg`,
  },
  {
    id: 5,
    nombre: "jordan 1 rojas",
    tipo: "zapatilla",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$67200",
    talle: "37",
    img: `./img/jordan/paul-volkmer-updW-QUccFE-unsplash.jpg`,
  },
  {
    id: 6,
    nombre: "jordan 23 blancas",
    tipo: "zapatilla",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$67200",
    talle: "39",
    img: `./img/jordan/hermes-rivera-wz_eb7K2Ip8-unsplash.jpg`,
  },
  {
    id: 7,
    nombre: "jordan 1 ",
    tipo: "zapatilla",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$67200",
    talle: "40",
    img: `./img/jordan/paul-volkmer-AZf7DL-8Qhk-unsplash.jpg`,
  },
  {
    id: 8,
    nombre: "jordan 4 retro amarilla",
    tipo: "zapatilla",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$67200",
    talle: "31",
    img: `./img/jordan/donald-martinez-heOfXZQTRIs-unsplash.jpg`,
  },
  {
    id: 9,
    nombre: "jordan 11 gris",
    tipo: "zapatilla",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$67200",
    talle: "37",
    img: `./img/jordan/donald-martinez-Jfghc6MGpt0-unsplash.jpg`,
  },
  {
    id: 10,
    nombre: "jordan 1 violetas",
    tipo: "zapatilla",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$$67200",
    talle: "39",
    img: `./img/jordan/moradas.jpg`,
  },
  {
    id: 11,
    nombre: "buzo overside",
    tipo: "buzo",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$7.200",
    talle: "s",
    img: `../img/buzos/velvet.jpg`,
  },
  {
    id: 12,
    nombre: "buzo overside",
    tipo: "buzo",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$5.300",
    talle: "M",
    img: `./img/buzos/flame.jpg`,
  },
  {
    id: 13,
    nombre: "buzo overside",
    tipo: "buzo",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$3.500",
    talle: "L",
    img: `./img/buzos/sakura.jpg`,
  },
  {
    id: 14,
    nombre: "buzo overside",
    tipo: "buzo",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$4.800",
    talle: "XL",
    img: `./img/buzos/blanco.jpg`,
  },
  {
    id: 15,
    nombre: "buzo overside",
    tipo: "buzo",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$7.840",
    talle: "XL",
    img: `./img/buzos/ninja.jpg`,
  },
  {
    id: 16,
    nombre: "buzo overside",
    tipo: "buzo",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$7.200",
    talle: "XL",
    img: `./img/buzos/acid.jpg`,
  },
  {
    id: 17,
    nombre: "buzo overside",
    tipo: "buzo",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$5.300",
    talle: "XL",
    img: `./img/buzos/amarilo.jpg`,
  },
  {
    id: 18,
    nombre: "buzo overside",
    tipo: "buzo",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$6.500",
    talle: "XL",
    img: `./img/buzos/oni.jpg`,
  },
  {
    id: 19,
    nombre: "buzo overside",
    tipo: "buzo",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$5.300",
    talle: "XL",
    img: `./img/buzos/gris.jpg`,
  },
  {
    id: 20,
    nombre: "buzo overside",
    tipo: "buzo",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$5.300",
    talle: "XL",
    img: `./img/buzos/buzoNegro.jpg`,
  },
  
// pantalones
  {
    id: 21,
    nombre: "Pantalon Cargo",
    tipo: "pantalono",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$8.200",
    talle: "s",
    img: `./img/pantalones/blanco.jpg`,
  },
  {
    id: 22,
    nombre: "Pantalon Cargo",
    tipo: "pantalon",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$9.300",
    talle: "M",
    img: `./img/pantalones/negro.jpg`,
  },
  {
    id: 23,
    nombre: "Pantalon Cargo",
    tipo: "pantalon",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$10.500",
    talle: "L",
    img: `./img/pantalones/streetwear.jpg`,
  },
  {
    id: 24,
    nombre: "Pantalon Cargo",
    tipo: "pantalon",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$8.800",
    talle: "XL",
    img: `./img/pantalones/rojo-negro.jpg`,
  },
  {
    id: 25,
    nombre: "Pantalon Cargo",
    tipo: "pantalon",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$7.840",
    talle: "XL",
    img: `./img/pantalones/blanco-negro.jpg`,
  },
  {
    id: 26,
    nombre: "Pantalon Cargo",
    tipo: "pantalon",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$7.200",
    talle: "XL",
    img: `./img/pantalones/mujer.jpg`,
  },
  {
    id: 27,
    nombre: "Pantalon Cargo",
    tipo: "pantalon",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$5.300",
    talle: "XL",
    img: `./img/pantalones/concadenas.jpg`,
  },
  {
    id: 28,
    nombre: "Pantalon Cargo",
    tipo: "pantalon",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$6.500",
    talle: "XL",
    img: `./img/pantalones/rosa.jpg`,
  },
  {
    id: 29,
    nombre: "Pantalon Cargo",
    tipo: "pantalon",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$7.500",
    talle: "XL",
    img: `./img/pantalones/naranja.jpg`,
  },
  {
    id: 30,
    nombre: "Pantalon Cargo",
    tipo: "pantalon",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$9.840",
    talle: "XL",
    img: `./img/pantalones/amarillo.jpg`,
  },

  // remeras
  {
    id: 31,
    nombre: "remeras",
    tipo: "remera",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$10.200",
    talle: "s",
    img: `./img/remeras/big.jpg`,
  },
  {
    id: 32,
    nombre: "remeras",
    tipo: "remera",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$8.300",
    talle: "M",
    img: `./img/remeras/remera.jpg`,
  },
  {
    id: 33,
    nombre: "remeras",
    tipo: "remera",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$3.300",
    talle: "L",
    img: `./img/remeras/cyber.jpg`,
  },
  {
    id: 34,
    nombre: "remeras",
    tipo: "remera",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$4.800",
    talle: "XL",
    img: `./img/remeras/remera-blanca.jpg`,
  },
  {
    id: 35,
    nombre: "remeras",
    tipo: "remera",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$14.840",
    talle: "XL",
    img: `./img/remeras/godface.jpg`,
  },
  {
    id: 36,
    nombre: "remeras",
    tipo: "remera",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$14.200",
    talle: "XL",
    img: `./img/remeras/black-shadow.jpg`,
  },
  {
    id: 37,
    nombre: "remeras",
    tipo: "remera",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$5.300",
    talle: "XL",
    img: `./img/remeras/manteca1.jpg`,
  },
  {
    id: 38,
    nombre: "remeras",
    tipo: "remera",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$13.500",
    talle: "XL",
    img: `./img/remeras/whatch.jpg`,
  },
  {
    id: 39,
    nombre: "remeras",
    tipo: "remera",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$10.800",
    talle: "XL",
    img: `./img/remeras/free-youth.jpg`,
  },
  {
    id: 40,
    nombre: "remeras",
    tipo: "remera",
    cantidad: 10,
    desc: "las mas facheras de jazstina",
    precio: "$17.840",
    talle: "XL",
    img: `./img/remeras/poison-blanco1poison.jpg`,
  },
];








